### ISSUE TITLE
Documentation not reflecting the actual state of Item syntax

### ISSUE THREAD

**Issue by halvko** [adamAndMath/RandomLoot#1]
While it would be nice if we were able to parse item files like explained in README.md, that is currently not the case, and i believe documentation should follow functionality, not the other way around.

A solution could be to remove the entry, and create an issue tracking the progress of the type system, or create a "TODO" section in the README.

**Comment by adamAndMath** [comment]
The goal should always be view-able. So as long as the information doesn't disappear, but rather is moved, I'd be happy with that
